const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Rex_RotateTo,
		C3.Behaviors.Physics,
		C3.Behaviors.Rex_MoveTo,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.TextBox,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Plugins.AJAX,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Plugins.Share,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Signal,
		C3.ScriptsInEvents.Both_Event1_Act6,
		C3.ScriptsInEvents.Both_Event1_Act8,
		C3.ScriptsInEvents.Both_Event1_Act9,
		C3.ScriptsInEvents.Both_Event2_Act5,
		C3.ScriptsInEvents.Both_Event2_Act7,
		C3.ScriptsInEvents.Both_Event2_Act8,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.X,
		C3.ScriptsInEvents.Both_Event63_Act8,
		C3.ScriptsInEvents.Both_Event63_Act9,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.ScriptsInEvents.Both_Event140_Act2,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.ScriptsInEvents.Both_Event141_Act2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.Both_Event143_Act2,
		C3.ScriptsInEvents.Both_Event145_Act5,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.ScriptsInEvents.Both_Event145_Act7,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.ScriptsInEvents.Both_Event155_Act2,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.ScriptsInEvents.Cpl_localization_Event3_Act1,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Acts.Destroy,
		C3.ScriptsInEvents.Matching_Event3_Act8,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.ScriptsInEvents.Matching_Event16_Act1,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.PickAll,
		C3.ScriptsInEvents.Matching_Event73_Act1,
		C3.ScriptsInEvents.Matching_Event73_Act13,
		C3.ScriptsInEvents.Matching_Event78_Act7,
		C3.ScriptsInEvents.Matching_Event78_Act9,
		C3.ScriptsInEvents.Matching_Event78_Act14,
		C3.ScriptsInEvents.Matching_Event78_Act15,
		C3.ScriptsInEvents.Matching_Event78_Act26,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnStart,
		C3.ScriptsInEvents.Matching_Event145_Act1,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.ScriptsInEvents.Matching_Event150_Act1,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Browser.Cnds.IsOnline,
		C3.Behaviors.Rex_RotateTo.Acts.SetActivated,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Rex_RotateTo.Acts.SetTargetAngleByDeltaAngle,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.ScriptsInEvents.Game_Event12_Act8,
		C3.Behaviors.lunarray_LiteTween.Acts.Reverse,
		C3.ScriptsInEvents.Game_Event13_Act8,
		C3.ScriptsInEvents.Game_Event14_Act8,
		C3.ScriptsInEvents.Game_Event15_Act15,
		C3.ScriptsInEvents.Game_Event16_Act14,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.ScriptsInEvents.Game_Event28_Act6,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Rex_MoveTo.Acts.Stop,
		C3.Behaviors.Rex_MoveTo.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Rex_MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.Rex_MoveTo.Acts.SetTargetPos,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Rex_MoveTo.Cnds.CompareSpeed,
		C3.Behaviors.Rex_MoveTo.Cnds.IsMoving,
		C3.ScriptsInEvents.Game_Event38_Act2,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.ScriptsInEvents.Game_Event41_Act3,
		C3.ScriptsInEvents.Game_Event41_Act4,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Rex_MoveTo.Acts.SetCurrentSpeed,
		C3.ScriptsInEvents.Game_Event107_Act2,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.ScriptsInEvents.Game_Event115_Act3,
		C3.ScriptsInEvents.Game_Event115_Act4,
		C3.ScriptsInEvents.Game_Event118_Act2,
		C3.ScriptsInEvents.Game_Event118_Act8,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.ScriptsInEvents.Game_Event128_Act3,
		C3.ScriptsInEvents.Game_Event129_Act3,
		C3.ScriptsInEvents.Game_Event129_Act4,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar.Acts.SetValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.ScriptsInEvents.Game_Event142_Act2,
		C3.ScriptsInEvents.Game_Event175_Act1,
		C3.ScriptsInEvents.Game_Event175_Act2,
		C3.ScriptsInEvents.Game_Event177_Act18,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.ScriptsInEvents.Game_Event181_Act2,
		C3.ScriptsInEvents.Game_Event186_Act11,
		C3.ScriptsInEvents.Game_Event195_Act2,
		C3.ScriptsInEvents.Game_Event195_Act4,
		C3.ScriptsInEvents.Game_Event197_Act1,
		C3.ScriptsInEvents.Game_Event197_Act2,
		C3.ScriptsInEvents.Game_Event201_Act1,
		C3.ScriptsInEvents.Game_Event201_Act2,
		C3.ScriptsInEvents.Game_Event202_Act1,
		C3.ScriptsInEvents.Game_Event203_Act1,
		C3.ScriptsInEvents.Game_Event206_Act1,
		C3.ScriptsInEvents.Game_Event207_Act1,
		C3.ScriptsInEvents.Game_Event207_Act3,
		C3.ScriptsInEvents.Game_Event208_Act1,
		C3.ScriptsInEvents.Game_Event208_Act2,
		C3.ScriptsInEvents.Game_Event212_Act1,
		C3.ScriptsInEvents.Game_Event243_Act2,
		C3.ScriptsInEvents.Game_Event244_Act3,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.ScriptsInEvents.Game_Event279_Act1,
		C3.ScriptsInEvents.Game_Event448_Act1,
		C3.ScriptsInEvents.Game_Event450_Act2,
		C3.ScriptsInEvents.Game_Event450_Act3,
		C3.ScriptsInEvents.Game_Event451_Act2,
		C3.ScriptsInEvents.Game_Event451_Act3,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetWebFont,
		C3.ScriptsInEvents.Splash_Event9_Act1,
		C3.ScriptsInEvents.Splash_Event10_Act3,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.TextBox.Exps.Text,
		C3.ScriptsInEvents.Joinorcreate_Event15_Act7,
		C3.ScriptsInEvents.Joinorcreate_Event15_Act24,
		C3.ScriptsInEvents.Joinorcreate_Event16_Act7,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.ScriptsInEvents.Joinorcreate_Event20_Act2,
		C3.ScriptsInEvents.Joinorcreate_Event21_Act2,
		C3.Plugins.TextBox.Acts.SetPlaceholder,
		C3.Plugins.TextBox.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.ScriptsInEvents.Cpl_game_Event15_Act2,
		C3.ScriptsInEvents.Cpl_game_Event15_Act4,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.ScriptsInEvents.Cpl_game_Event27_Act4,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.ScriptsInEvents.Cpl_game_Event102_Act1,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.ScriptsInEvents.Cpl_game_Event166_Act6,
		C3.ScriptsInEvents.Cpl_game_Event167_Act5,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.ScriptsInEvents.Cpl_game_Event197_Act39,
		C3.ScriptsInEvents.Cpl_game_Event199_Act4,
		C3.ScriptsInEvents.Cpl_game_Event199_Act6,
		C3.ScriptsInEvents.Cpl_game_Event207_Act36,
		C3.ScriptsInEvents.Cpl_game_Event218_Act37,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Behaviors.lunarray_LiteTween.Acts.Stop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.ScriptsInEvents.Cpl_game_Event279_Act1,
		C3.ScriptsInEvents.Cpl_game_Event279_Act8,
		C3.ScriptsInEvents.Cpl_game_Event295_Act37,
		C3.ScriptsInEvents.Cpl_game_Event304_Act38,
		C3.ScriptsInEvents.Cpl_game_Event312_Act38,
		C3.Behaviors.Rex_MoveTo.Cnds.OnHitTarget,
		C3.ScriptsInEvents.Cpl_game_Event353_Act1,
		C3.ScriptsInEvents.Cpl_game_Event356_Act2,
		C3.ScriptsInEvents.Cpl_game_Event361_Act1,
		C3.ScriptsInEvents.Cpl_game_Event366_Act3,
		C3.ScriptsInEvents.Cpl_game_Event430_Act1,
		C3.ScriptsInEvents.Cpl_game_Event430_Act28,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Acts.SetLayerTransparent,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Acts.SetX,
		C3.ScriptsInEvents["Cpl_vs-Screen_Event3_Act7"],
		C3.ScriptsInEvents["Cpl_vs-Screen_Event1208_Act1"],
		C3.Plugins.System.Acts.ResetGlobals,
		C3.ScriptsInEvents.Cpl_splash_Event10_Act3,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.ScriptsInEvents.Cpl_splash_Event16_Act2,
		C3.ScriptsInEvents.Cpl_splash_Event16_Act6,
		C3.ScriptsInEvents.Cpl_splash_Event16_Act7,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnReverseEnd,
		C3.Plugins.Browser.Acts.Close,
		C3.ScriptsInEvents.Cpl_splash_Event100_Act2,
		C3.ScriptsInEvents.Cpl_splash_Event102_Act3,
		C3.ScriptsInEvents.Cpl_splash_Event104_Act3,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{LiteTween: 0},
	{FullscreenBtn: 0},
	{Create: 0},
	{Destroy: 0},
	{RotateTo: 0},
	{Physics: 0},
	{MoveTo: 0},
	{cpl_Ball: 0},
	{cpl_Sprite3: 0},
	{cpl_bb: 0},
	{cpl_RunsNumbers: 0},
	{Touch: 0},
	{cpl_Wicket: 0},
	{cpl_Sprite8: 0},
	{cpl_Wicket2: 0},
	{cpl_Sprite9: 0},
	{cpl_NeedRuns: 0},
	{cpl_BallsLeft: 0},
	{cpl_WicketLeft: 0},
	{cpl_Particles: 0},
	{cpl_Pitch: 0},
	{cpl_Light: 0},
	{Browser: 0},
	{LiteTween2: 0},
	{LiteTween3: 0},
	{cpl_FullscreenBtn: 0},
	{cpl_CKlogo: 0},
	{cpl_DDlogo: 0},
	{cpl_PLlogo: 0},
	{cpl_KRlogo: 0},
	{cpl_MWlogo: 0},
	{cpl_RClogo: 0},
	{cpl_BSlogo: 0},
	{cpl_HSlogo: 0},
	{cpl_ChooseYourTeam: 0},
	{cpl_Overs: 0},
	{Tween: 0},
	{cpl_Playhello: 0},
	{cpl_ChooseYourTeam2: 0},
	{cpl_Sprite4: 0},
	{cpl_targetboard: 0},
	{cpl_BatsmanScoreText: 0},
	{cpl_HitRuns: 0},
	{cpl_SpriteFont: 0},
	{cpl_CKname: 0},
	{cpl_MWname: 0},
	{cpl_KRname: 0},
	{cpl_DDname: 0},
	{cpl_BSname: 0},
	{cpl_HSname: 0},
	{cpl_PLname: 0},
	{cpl_RCname: 0},
	{cpl_CKmatchplayed: 0},
	{cpl_MWmatchplayed: 0},
	{cpl_KRmatchplayed: 0},
	{cpl_DDmatchplayed: 0},
	{cpl_HSmatchplayed: 0},
	{cpl_PLmatchplayed: 0},
	{cpl_RCmatchplayed: 0},
	{cpl_CKmatchwin: 0},
	{cpl_MWmatchwin: 0},
	{cpl_KRmatchwin: 0},
	{cpl_DDmatchwin: 0},
	{cpl_BSmatchwin: 0},
	{cpl_HSmatchwin: 0},
	{cpl_PLmatchwin: 0},
	{cpl_RCmatchwin: 0},
	{cpl_CKmatchloss: 0},
	{cpl_MWmatchloss: 0},
	{cpl_KRmatchloss: 0},
	{cpl_DDmatchloss: 0},
	{cpl_HSmatchloss: 0},
	{cpl_PLmatchloss: 0},
	{cpl_RCmatchloss: 0},
	{cpl_TextBox: 0},
	{cpl_PlayerName: 0},
	{LocalStorage: 0},
	{cpl_Team1st: 0},
	{cpl_vs: 0},
	{cpl_CKmatchpoints: 0},
	{cpl_MWmatchpoints: 0},
	{cpl_KRmatchpoints: 0},
	{cpl_DDmatchpoints: 0},
	{cpl_HSmatchpoints: 0},
	{cpl_PLmatchpoints: 0},
	{cpl_RCmatchpoints: 0},
	{cpl_Keyboard: 0},
	{cpl_Restart: 0},
	{cpl_Sprite10: 0},
	{cpl_logo: 0},
	{cpl_Home: 0},
	{cpl_NextMatchText: 0},
	{click: 0},
	{cpl_Sprite16: 0},
	{cpl_Array: 0},
	{cpl_MatchesCategories: 0},
	{cpl_chooseyourteam3: 0},
	{cpl_whitesprite: 0},
	{cpl_nextbtn: 0},
	{cpl_matchbetween: 0},
	{cpl_vs2: 0},
	{cpl_shadow: 0},
	{cpl_Team1sttxt: 0},
	{cpl_shadow2: 0},
	{cpl_Team2sttxt: 0},
	{Fade: 0},
	{cpl_SeriesLossOrWin: 0},
	{cpl_StartingScoreText: 0},
	{cpl_PausePlay: 0},
	{cpl_PauseBtn: 0},
	{cpl_321newtext: 0},
	{cpl_loosewon: 0},
	{cpl_pausetext: 0},
	{cpl_SoundBtn: 0},
	{Audio: 0},
	{cpl_tournementloosewin: 0},
	{cpl_cup: 0},
	{ScrollTo: 0},
	{cpl_shakeme: 0},
	{cpl_conf: 0},
	{cpl_Teamnames: 0},
	{cpl_vs3: 0},
	{cpl_yourteam: 0},
	{cpl_TutorialText: 0},
	{cpl_Tutorial: 0},
	{cpl_Sprite2: 0},
	{type: 0},
	{cpl_Player: 0},
	{cpl_Sprite14: 0},
	{Pin: 0},
	{cpl_Ball_Shadow: 0},
	{cpl_ballfontt: 0},
	{cpl_singlematch: 0},
	{cpl_scoreboard2: 0},
	{cpl_singlescore: 0},
	{cpl_besttext: 0},
	{cpl_best: 0},
	{cpl_black321: 0},
	{cpl_reset: 0},
	{cpl_backbtn: 0},
	{AJAX: 0},
	{cpl_LuknowSGlogo: 0},
	{cpl_gujratlogo: 0},
	{cpl_Team2nd: 0},
	{pausetext: 0},
	{StartingScoreText: 0},
	{besttext: 0},
	{"321newtext": 0},
	{yourinfo: 0},
	{opponentinfo: 0},
	{Particles: 0},
	{Pitch: 0},
	{Sprite4: 0},
	{Sprite14: 0},
	{bb: 0},
	{Ball_Shadow: 0},
	{Sprite8: 0},
	{Sticker: 0},
	{Wicket2: 0},
	{RunsNumbers: 0},
	{RunNumber: 0},
	{scoremaincfont: 0},
	{Score_BG: 0},
	{Restart: 0},
	{PauseBtn: 0},
	{conf: 0},
	{Tutorial: 0},
	{whitebar: 0},
	{SpriteFont: 0},
	{leaderboard: 0},
	{Home: 0},
	{SoundBtn: 0},
	{shakeme: 0},
	{Confettii_Destroy: 0},
	{taptohittheshot: 0},
	{Sprite5: 0},
	{hitcollider: 0},
	{exitbtn: 0},
	{PlayerTwoIcon: 0},
	{PlayerOneIcon: 0},
	{FirstTime: 0},
	{BowlingInfo: 0},
	{BallCountIcon: 0},
	{BallLocationConfirmBT: 0},
	{Sine: 0},
	{tapOnIconSprite: 0},
	{arrow: 0},
	{charac: 0},
	{hero1: 0},
	{cameraa: 0},
	{ballLocation: 0},
	{Powerbar: 0},
	{temppowerindicator: 0},
	{TempBallLoc: 0},
	{board: 0},
	{YourScoreSF: 0},
	{opponentScoreSF: 0},
	{PowerbarFront: 0},
	{YourScoreSFFinal: 0},
	{opponentScoreSFFinal: 0},
	{PowerBarTG: 0},
	{Sprite2: 0},
	{Sprite10: 0},
	{Rotate: 0},
	{Sprite13: 0},
	{MoveTo2: 0},
	{Ball: 0},
	{powermeter: 0},
	{rematchdiaIcon: 0},
	{GameResult: 0},
	{GameOverIcon: 0},
	{newmatch: 0},
	{rematch: 0},
	{yes: 0},
	{no: 0},
	{powerindicator: 0},
	{powerindicatorfront: 0},
	{arrow2: 0},
	{ExitScreen: 0},
	{ExitDialogBox: 0},
	{DoYouWantToExitSprite: 0},
	{NoExitBt: 0},
	{YesExitBt: 0},
	{Sprite9: 0},
	{Wicket: 0},
	{PausePlay: 0},
	{InningsDoneIcon: 0},
	{inningDone: 0},
	{cricketliveBg: 0},
	{splashYourName: 0},
	{Sprite6: 0},
	{SplashBatSwing: 0},
	{Play: 0},
	{Sprite: 0},
	{Sprite12: 0},
	{dirt: 0},
	{loadingtext: 0},
	{fxlogo: 0},
	{bar: 0},
	{yourname: 0},
	{timersec: 0},
	{findingamatch: 0},
	{opponentname: 0},
	{MatchMakingFrame: 0},
	{MatchMakingNameCard: 0},
	{MatchmakingVS: 0},
	{batorballside: 0},
	{MatchingScreen: 0},
	{matchingBG: 0},
	{multiplayerBttn: 0},
	{langbtn: 0},
	{leaderboard2: 0},
	{backbtn: 0},
	{logocheck: 0},
	{adboard: 0},
	{watchanadtext: 0},
	{yesad: 0},
	{noad: 0},
	{Overs2: 0},
	{splashExitBoard: 0},
	{splashExityes: 0},
	{splashExitno: 0},
	{splashTxt: 0},
	{Sprite11: 0},
	{moreGameButton: 0},
	{Share: 0},
	{checkBoard: 0},
	{exitbtn2: 0},
	{playOnline: 0},
	{PlayWithFriends: 0},
	{JoinFullBoard: 0},
	{createBttn: 0},
	{Jointbttn: 0},
	{invitePlayer: 0},
	{newJoin: 0},
	{TextInput: 0},
	{MatchCodebOARD: 0},
	{MatchCodetext: 0},
	{textPlaywith: 0},
	{Sprite15: 0},
	{entercodeBAr: 0},
	{emojibar: 0},
	{playOnlineMainBoard: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{notice: 0},
	{okBttn: 0},
	{Sprite3: 0},
	{backBtn2: 0},
	{goback: 0},
	{waitforplayer: 0},
	{dot: 0},
	{Sprite19: 0},
	{gameoverHome: 0},
	{timerBallIcon: 0},
	{FastRadialProgressBar: 0},
	{timerCircle: 0},
	{AutoBalltimetext: 0},
	{yourteamName: 0},
	{opponentTeamname: 0},
	{Sprite20: 0},
	{Text: 0},
	{cpl_totalOvers: 0},
	{Sprite7: 0},
	{tutorialMode: 0},
	{missed: 0},
	{tutPlayconsent: 0},
	{Sprite16: 0},
	{Sprite21: 0},
	{whatAShot_: 0},
	{Sprite22: 0},
	{timerCircle2: 0},
	{timertxt: 0},
	{PlayerOneIcon2: 0},
	{TIMESUP: 0},
	{camm: 0},
	{Textlicense: 0},
	{PlatformInfo: 0},
	{cpl_TeamRankingText: 0},
	{cpl_BSrankingText: 0},
	{cpl_CSrankingText: 0},
	{cpl_DDrankingText: 0},
	{cpl_HSrankingText: 0},
	{cpl_KRrankingText: 0},
	{cpl_MWrankingText: 0},
	{cpl_RCrankingText: 0},
	{cpl_PLrankingText: 0},
	{cpl_teamicons: 0},
	{Splash: 0},
	{cplobjects: 0},
	{clojects: 0},
	{bowlerFrame: 0},
	{BowlerJeasey: 0},
	{BowlerJeasey2: 0},
	{BatsmanJeasey: 0},
	{BatsmanJeasey2: 0},
	{BatsmanTeam: 0},
	{bowlerNameDummy: 0},
	{batsmanNameDummy: 0},
	{BowlerTeam: 0},
	{batsmanFrame: 0},
	{name: 0},
	{picFrame: 0},
	{jersey: 0},
	{Variable2: 0},
	{AutoBallTime: 0},
	{ballTriggeredfromgame: 0},
	{gamecompletecool: 0},
	{yourFrame: 0},
	{timeSec: 0},
	{matched: 0},
	{botMode: 0},
	{botName: 0},
	{botFrame: 0},
	{bgFrameGlobal: 0},
	{botMtachTime: 0},
	{matchingButtonClicked: 0},
	{botNameDummy: 0},
	{serverwentOffline: 0},
	{sessionIDGlob: 0},
	{sessionID: 0},
	{Variable1: 0},
	{bgFrame: 0},
	{checkNet: 0},
	{confetti: 0},
	{OpponentTeamName: 0},
	{FinalLosser: 0},
	{FinalWinner: 0},
	{FirstTimeStart: 0},
	{StartFrame: 0},
	{MatchCount: 0},
	{ChennaiWin: 0},
	{MumbaiWin: 0},
	{KolkataWin: 0},
	{DelhiWin: 0},
	{BangloreWin: 0},
	{HyderabadWin: 0},
	{PunjabWin: 0},
	{RajasthanWin: 0},
	{ChennaiLoss: 0},
	{MumbaiLoss: 0},
	{KolkataLoss: 0},
	{DelhiLoss: 0},
	{BangloreLoss: 0},
	{HyderabadLoss: 0},
	{PunjabLoss: 0},
	{RajasthanLoss: 0},
	{ChennaiTie: 0},
	{MumbaiTie: 0},
	{KolkataTie: 0},
	{DelhiTie: 0},
	{BangloreTie: 0},
	{HyderabadTie: 0},
	{PunjabTie: 0},
	{RajasthanTie: 0},
	{mainvalue: 0},
	{MatchesFromDifferentTeams: 0},
	{BallCreate: 0},
	{TotalWicket: 0},
	{s2: 0},
	{Counter_Score: 0},
	{FontSize: 0},
	{HitRuns: 0},
	{BatsmanScore: 0},
	{Win: 0},
	{Loss: 0},
	{StartingLight: 0},
	{BallDestroy: 0},
	{BallsLeft: 0},
	{NeedRuns: 0},
	{WicketLeft: 0},
	{s3: 0},
	{s1: 0},
	{allover: 0},
	{ballLocationX: 0},
	{tempballY: 0},
	{powerindicatorY: 0},
	{cursorXGlobal: 0},
	{ballPowerGlobal: 0},
	{batHitValue: 0},
	{batHitGlobal: 0},
	{ballx2: 0},
	{bally2: 0},
	{ballX: 0},
	{ballXGlobal: 0},
	{ballorbat: 0},
	{batsmanName: 0},
	{bowlerName: 0},
	{ballturn: 0},
	{ballcount: 0},
	{yourScore: 0},
	{opponentScore: 0},
	{result: 0},
	{rematchOrNext: 0},
	{botVSplayer: 0},
	{GameStarted: 0},
	{FirstBall: 0},
	{firstInningDone: 0},
	{botscore: 0},
	{shot: 0},
	{shot2: 0},
	{balltimerr: 0},
	{showingbar: 0},
	{checkball: 0},
	{sendscore: 0},
	{checkstart: 0},
	{firsttimeAnimation: 0},
	{Variable4: 0},
	{f1: 0},
	{f2: 0},
	{f3: 0},
	{s3T: 0},
	{f0: 0},
	{tutorial2: 0},
	{cursor: 0},
	{ballPower: 0},
	{hitValue: 0},
	{ballXorMiss: 0},
	{score: 0},
	{score2: 0},
	{botLevel: 0},
	{destroyconf: 0},
	{bowlingGroup: 0},
	{battingGroup: 0},
	{param: 0},
	{ballcountgamecomplete: 0},
	{animation: 0},
	{BallCountmirror: 0},
	{level1MissProb: 0},
	{level2MissProb: 0},
	{level3MissProb: 0},
	{level4MissProb: 0},
	{level5MissProb: 0},
	{"1HIt": 0},
	{"2hit": 0},
	{"3hit": 0},
	{"4hit": 0},
	{"6hit": 0},
	{alreadyhit: 0},
	{hit6: 0},
	{hit4: 0},
	{hit1: 0},
	{hit2: 0},
	{hit3: 0},
	{batsmanteamname: 0},
	{bowlerteamname: 0},
	{botTeamname: 0},
	{Variable3: 0},
	{best: 0},
	{sound: 0},
	{check1: 0},
	{full: 0},
	{fullscreen: 0},
	{TotalMatches: 0},
	{QuaterFinal: 0},
	{Stage: 0},
	{TeamChangeGroup: 0},
	{Team2nd: 0},
	{Team2ndFrame: 0},
	{next: 0},
	{PlayerName: 0},
	{SelectName: 0},
	{SelectedTeam: 0},
	{Rajasthan: 0},
	{Punjab: 0},
	{Hyderabad: 0},
	{Banglore: 0},
	{Delhi: 0},
	{Kolkata: 0},
	{Mumbai: 0},
	{Chennai: 0},
	{ChooseOver: 0},
	{TeamSelect: 0},
	{pitchballsound: 0},
	{serverConnected: 0},
	{PlayClick: 0},
	{touchedanyoftwo: 0},
	{createOrNot: 0},
	{roomCodeJoin: 0},
	{roomCodeCreate: 0},
	{playWithFriends: 0},
	{joinOrCreateClicked: 0},
	{onStart: 0},
	{JoinMatch: 0},
	{createMatch: 0},
	{joinmatchTouched: 0},
	{stopRes: 0},
	{InvitePlayer: 0},
	{invalidcodeornot: 0},
	{backbbtn: 0},
	{isOk: 0},
	{Rewardtype: 0},
	{cpl_Score: 0},
	{cpl_confetti: 0},
	{cpl_OpponentTeamName: 0},
	{cpl_FinalLosser: 0},
	{cpl_FirstTimeStart: 0},
	{cpl_Touch: 0},
	{cpl_MatchCount: 0},
	{cpl_ChennaiWin: 0},
	{cpl_MumbaiWin: 0},
	{cpl_KolkataWin: 0},
	{cpl_DelhiWin: 0},
	{cpl_BangloreWin: 0},
	{cpl_HyderabadWin: 0},
	{cpl_PunjabWin: 0},
	{cpl_RajasthanWin: 0},
	{cpl_ChennaiLoss: 0},
	{cpl_MumbaiLoss: 0},
	{cpl_KolkataLoss: 0},
	{cpl_DelhiLoss: 0},
	{cpl_BangloreLoss: 0},
	{cpl_HyderabadLoss: 0},
	{cpl_PunjabLoss: 0},
	{cpl_RajasthanLoss: 0},
	{cpl_BallCreate: 0},
	{cpl_TotalWicket: 0},
	{cpl_TotalRuns: 0},
	{cpl_FontSize: 0},
	{cpl_BatsmanScore: 0},
	{cpl_Win: 0},
	{cpl_Loss: 0},
	{cpl_StartingLight: 0},
	{cpl_BallDestroy: 0},
	{throughreward: 0},
	{tutScreen: 0},
	{Ad: 0},
	{totalBallsPlayed: 0},
	{goforPractice: 0},
	{shotsHit: 0},
	{SESSION: 0},
	{RewardAvail: 0},
	{cpl_sound: 0},
	{cpl_check1: 0},
	{cpl_full: 0},
	{cpl_fullscreen: 0},
	{cpl_next: 0},
	{cpl_SelectName: 0},
	{cpl_SelectedTeam: 0},
	{cpl_Rajasthan: 0},
	{cpl_Punjab: 0},
	{cpl_Hyderabad: 0},
	{cpl_Banglore: 0},
	{cpl_Delhi: 0},
	{cpl_Kolkata: 0},
	{cpl_Mumbai: 0},
	{cpl_Chennai: 0},
	{cpl_ChooseOver: 0},
	{cpl_TeamSelect: 0},
	{cpl_TeamSelectstring: 0},
	{playBttn: 0},
	{cpl_pong: 0},
	{myTeam: 0},
	{checktween: 0},
	{checkVs: 0},
	{cpl_TotalMatches: 0},
	{cpl_QuaterFinal: 0},
	{cpl_Stage: 0},
	{cpl_TeamChangeGroup: 0},
	{cpl_Team2ndFrame: 0},
	{cplorCricketlive: 0},
	{cpl_PlayClick: 0},
	{langScreen: 0},
	{firsttimescreen: 0},
	{langSelected: 0},
	{timeofAd: 0},
	{playerNameDummy: 0},
	{langlocal: 0},
	{mainclicked: 0},
	{startOn: 0},
	{singlePopUp: 0},
	{exitTouch: 0},
	{online: 0},
	{cpl_LngParma: 0},
	{Check: 0},
	{cmplg: 0},
	{FsLock: 0},
	{logoFast: 0}
];

self.InstanceType = {
	FullscreenBtn: class extends self.ISpriteInstance {},
	cpl_Ball: class extends self.ISpriteInstance {},
	cpl_Sprite3: class extends self.ISpriteInstance {},
	cpl_bb: class extends self.ISpriteInstance {},
	cpl_RunsNumbers: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	cpl_Wicket: class extends self.ISpriteInstance {},
	cpl_Sprite8: class extends self.ISpriteInstance {},
	cpl_Wicket2: class extends self.ISpriteInstance {},
	cpl_Sprite9: class extends self.ISpriteInstance {},
	cpl_NeedRuns: class extends self.ITextInstance {},
	cpl_BallsLeft: class extends self.ITextInstance {},
	cpl_WicketLeft: class extends self.ITextInstance {},
	cpl_Particles: class extends self.IParticlesInstance {},
	cpl_Pitch: class extends self.ISpriteInstance {},
	cpl_Light: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	cpl_FullscreenBtn: class extends self.ISpriteInstance {},
	cpl_CKlogo: class extends self.ISpriteInstance {},
	cpl_DDlogo: class extends self.ISpriteInstance {},
	cpl_PLlogo: class extends self.ISpriteInstance {},
	cpl_KRlogo: class extends self.ISpriteInstance {},
	cpl_MWlogo: class extends self.ISpriteInstance {},
	cpl_RClogo: class extends self.ISpriteInstance {},
	cpl_BSlogo: class extends self.ISpriteInstance {},
	cpl_HSlogo: class extends self.ISpriteInstance {},
	cpl_ChooseYourTeam: class extends self.ITextInstance {},
	cpl_Overs: class extends self.ISpriteInstance {},
	cpl_Playhello: class extends self.ISpriteInstance {},
	cpl_ChooseYourTeam2: class extends self.ITextInstance {},
	cpl_Sprite4: class extends self.ISpriteInstance {},
	cpl_targetboard: class extends self.ISpriteInstance {},
	cpl_BatsmanScoreText: class extends self.ITextInstance {},
	cpl_HitRuns: class extends self.ITextInstance {},
	cpl_SpriteFont: class extends self.ISpriteFontInstance {},
	cpl_CKname: class extends self.ITextInstance {},
	cpl_MWname: class extends self.ITextInstance {},
	cpl_KRname: class extends self.ITextInstance {},
	cpl_DDname: class extends self.ITextInstance {},
	cpl_BSname: class extends self.ITextInstance {},
	cpl_HSname: class extends self.ITextInstance {},
	cpl_PLname: class extends self.ITextInstance {},
	cpl_RCname: class extends self.ITextInstance {},
	cpl_CKmatchplayed: class extends self.ITextInstance {},
	cpl_MWmatchplayed: class extends self.ITextInstance {},
	cpl_KRmatchplayed: class extends self.ITextInstance {},
	cpl_DDmatchplayed: class extends self.ITextInstance {},
	cpl_HSmatchplayed: class extends self.ITextInstance {},
	cpl_PLmatchplayed: class extends self.ITextInstance {},
	cpl_RCmatchplayed: class extends self.ITextInstance {},
	cpl_CKmatchwin: class extends self.ITextInstance {},
	cpl_MWmatchwin: class extends self.ITextInstance {},
	cpl_KRmatchwin: class extends self.ITextInstance {},
	cpl_DDmatchwin: class extends self.ITextInstance {},
	cpl_BSmatchwin: class extends self.ITextInstance {},
	cpl_HSmatchwin: class extends self.ITextInstance {},
	cpl_PLmatchwin: class extends self.ITextInstance {},
	cpl_RCmatchwin: class extends self.ITextInstance {},
	cpl_CKmatchloss: class extends self.ITextInstance {},
	cpl_MWmatchloss: class extends self.ITextInstance {},
	cpl_KRmatchloss: class extends self.ITextInstance {},
	cpl_DDmatchloss: class extends self.ITextInstance {},
	cpl_HSmatchloss: class extends self.ITextInstance {},
	cpl_PLmatchloss: class extends self.ITextInstance {},
	cpl_RCmatchloss: class extends self.ITextInstance {},
	cpl_TextBox: class extends self.ITextInputInstance {},
	cpl_PlayerName: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	cpl_Team1st: class extends self.ISpriteInstance {},
	cpl_vs: class extends self.ITextInstance {},
	cpl_CKmatchpoints: class extends self.ITextInstance {},
	cpl_MWmatchpoints: class extends self.ITextInstance {},
	cpl_KRmatchpoints: class extends self.ITextInstance {},
	cpl_DDmatchpoints: class extends self.ITextInstance {},
	cpl_HSmatchpoints: class extends self.ITextInstance {},
	cpl_PLmatchpoints: class extends self.ITextInstance {},
	cpl_RCmatchpoints: class extends self.ITextInstance {},
	cpl_Keyboard: class extends self.IInstance {},
	cpl_Restart: class extends self.ISpriteInstance {},
	cpl_Sprite10: class extends self.ISpriteInstance {},
	cpl_logo: class extends self.ISpriteInstance {},
	cpl_Home: class extends self.ISpriteInstance {},
	cpl_NextMatchText: class extends self.ITextInstance {},
	cpl_Sprite16: class extends self.ISpriteInstance {},
	cpl_Array: class extends self.IArrayInstance {},
	cpl_MatchesCategories: class extends self.ITextInstance {},
	cpl_chooseyourteam3: class extends self.ISpriteInstance {},
	cpl_whitesprite: class extends self.ISpriteInstance {},
	cpl_nextbtn: class extends self.ISpriteInstance {},
	cpl_matchbetween: class extends self.ISpriteInstance {},
	cpl_vs2: class extends self.ISpriteInstance {},
	cpl_shadow: class extends self.ISpriteInstance {},
	cpl_Team1sttxt: class extends self.ISpriteInstance {},
	cpl_shadow2: class extends self.ISpriteInstance {},
	cpl_Team2sttxt: class extends self.ISpriteInstance {},
	cpl_SeriesLossOrWin: class extends self.ISpriteInstance {},
	cpl_StartingScoreText: class extends self.ITextInstance {},
	cpl_PausePlay: class extends self.ISpriteInstance {},
	cpl_PauseBtn: class extends self.ISpriteInstance {},
	cpl_321newtext: class extends self.ITextInstance {},
	cpl_loosewon: class extends self.ITextInstance {},
	cpl_pausetext: class extends self.ITextInstance {},
	cpl_SoundBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	cpl_tournementloosewin: class extends self.ITextInstance {},
	cpl_cup: class extends self.ISpriteInstance {},
	cpl_shakeme: class extends self.ISpriteInstance {},
	cpl_conf: class extends self.ISpriteInstance {},
	cpl_Teamnames: class extends self.ISpriteInstance {},
	cpl_vs3: class extends self.ISpriteInstance {},
	cpl_yourteam: class extends self.ISpriteInstance {},
	cpl_TutorialText: class extends self.ITextInstance {},
	cpl_Tutorial: class extends self.ISpriteInstance {},
	cpl_Sprite2: class extends self.ISpriteInstance {},
	cpl_Player: class extends self.ISpriteInstance {},
	cpl_Sprite14: class extends self.ISpriteInstance {},
	cpl_Ball_Shadow: class extends self.ISpriteInstance {},
	cpl_ballfontt: class extends self.ISpriteFontInstance {},
	cpl_singlematch: class extends self.ISpriteInstance {},
	cpl_scoreboard2: class extends self.ISpriteInstance {},
	cpl_singlescore: class extends self.ITextInstance {},
	cpl_besttext: class extends self.ITextInstance {},
	cpl_best: class extends self.ISpriteInstance {},
	cpl_black321: class extends self.ISpriteInstance {},
	cpl_reset: class extends self.ISpriteInstance {},
	cpl_backbtn: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	cpl_LuknowSGlogo: class extends self.ISpriteInstance {},
	cpl_gujratlogo: class extends self.ISpriteInstance {},
	cpl_Team2nd: class extends self.ISpriteInstance {},
	pausetext: class extends self.ITextInstance {},
	StartingScoreText: class extends self.ITextInstance {},
	besttext: class extends self.ITextInstance {},
	_321newtext: class extends self.ITextInstance {},
	yourinfo: class extends self.ITextInstance {},
	opponentinfo: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Pitch: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	bb: class extends self.ISpriteInstance {},
	Ball_Shadow: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sticker: class extends self.ISpriteInstance {},
	Wicket2: class extends self.ISpriteInstance {},
	RunsNumbers: class extends self.ISpriteInstance {},
	RunNumber: class extends self.ISpriteInstance {},
	scoremaincfont: class extends self.ISpriteFontInstance {},
	Score_BG: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	PauseBtn: class extends self.ISpriteInstance {},
	conf: class extends self.ISpriteInstance {},
	Tutorial: class extends self.ISpriteInstance {},
	whitebar: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	leaderboard: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	SoundBtn: class extends self.ISpriteInstance {},
	shakeme: class extends self.ISpriteInstance {},
	Confettii_Destroy: class extends self.ISpriteInstance {},
	taptohittheshot: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	hitcollider: class extends self.ISpriteInstance {},
	exitbtn: class extends self.ISpriteInstance {},
	PlayerTwoIcon: class extends self.ISpriteInstance {},
	PlayerOneIcon: class extends self.ISpriteInstance {},
	BowlingInfo: class extends self.ISpriteInstance {},
	BallCountIcon: class extends self.ISpriteInstance {},
	BallLocationConfirmBT: class extends self.ISpriteInstance {},
	tapOnIconSprite: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	hero1: class extends self.ISpriteInstance {},
	cameraa: class extends self.ISpriteInstance {},
	ballLocation: class extends self.ISpriteInstance {},
	Powerbar: class extends self.ISpriteInstance {},
	temppowerindicator: class extends self.ISpriteInstance {},
	TempBallLoc: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	YourScoreSF: class extends self.ISpriteFontInstance {},
	opponentScoreSF: class extends self.ISpriteFontInstance {},
	PowerbarFront: class extends self.ISpriteInstance {},
	YourScoreSFFinal: class extends self.ISpriteFontInstance {},
	opponentScoreSFFinal: class extends self.ISpriteFontInstance {},
	PowerBarTG: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	powermeter: class extends self.ISpriteInstance {},
	rematchdiaIcon: class extends self.ISpriteInstance {},
	GameResult: class extends self.ISpriteInstance {},
	GameOverIcon: class extends self.ISpriteInstance {},
	newmatch: class extends self.ISpriteInstance {},
	rematch: class extends self.ISpriteInstance {},
	yes: class extends self.ISpriteInstance {},
	no: class extends self.ISpriteInstance {},
	powerindicator: class extends self.ISpriteInstance {},
	powerindicatorfront: class extends self.ISpriteInstance {},
	arrow2: class extends self.ISpriteInstance {},
	ExitScreen: class extends self.ISpriteInstance {},
	ExitDialogBox: class extends self.ISpriteInstance {},
	DoYouWantToExitSprite: class extends self.ISpriteInstance {},
	NoExitBt: class extends self.ISpriteInstance {},
	YesExitBt: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Wicket: class extends self.ISpriteInstance {},
	PausePlay: class extends self.ISpriteInstance {},
	InningsDoneIcon: class extends self.ISpriteInstance {},
	inningDone: class extends self.ISpriteInstance {},
	cricketliveBg: class extends self.ISpriteInstance {},
	splashYourName: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	SplashBatSwing: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	dirt: class extends self.ISpriteInstance {},
	loadingtext: class extends self.ITextInstance {},
	fxlogo: class extends self.ISpriteInstance {},
	bar: class extends self.ISpriteInstance {},
	yourname: class extends self.ITextInstance {},
	timersec: class extends self.ITextInstance {},
	findingamatch: class extends self.ITextInstance {},
	opponentname: class extends self.ITextInstance {},
	MatchMakingFrame: class extends self.ISpriteInstance {},
	MatchMakingNameCard: class extends self.ISpriteInstance {},
	MatchmakingVS: class extends self.ISpriteInstance {},
	batorballside: class extends self.ISpriteInstance {},
	MatchingScreen: class extends self.ISpriteFontInstance {},
	matchingBG: class extends self.ISpriteInstance {},
	multiplayerBttn: class extends self.ISpriteInstance {},
	langbtn: class extends self.ISpriteInstance {},
	leaderboard2: class extends self.ISpriteInstance {},
	backbtn: class extends self.ISpriteInstance {},
	logocheck: class extends self.ISpriteInstance {},
	adboard: class extends self.ISpriteInstance {},
	watchanadtext: class extends self.ISpriteInstance {},
	yesad: class extends self.ISpriteInstance {},
	noad: class extends self.ISpriteInstance {},
	Overs2: class extends self.ISpriteInstance {},
	splashExitBoard: class extends self.ISpriteInstance {},
	splashExityes: class extends self.ISpriteInstance {},
	splashExitno: class extends self.ISpriteInstance {},
	splashTxt: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	moreGameButton: class extends self.ISpriteInstance {},
	Share: class extends self.IInstance {},
	checkBoard: class extends self.ISpriteInstance {},
	exitbtn2: class extends self.ISpriteInstance {},
	playOnline: class extends self.ISpriteInstance {},
	PlayWithFriends: class extends self.ISpriteInstance {},
	JoinFullBoard: class extends self.ISpriteInstance {},
	createBttn: class extends self.ISpriteInstance {},
	Jointbttn: class extends self.ISpriteInstance {},
	invitePlayer: class extends self.ISpriteInstance {},
	newJoin: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	MatchCodebOARD: class extends self.ISpriteInstance {},
	MatchCodetext: class extends self.ITextInstance {},
	textPlaywith: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	entercodeBAr: class extends self.ISpriteInstance {},
	emojibar: class extends self.ISpriteInstance {},
	playOnlineMainBoard: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	notice: class extends self.ISpriteInstance {},
	okBttn: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	backBtn2: class extends self.ISpriteInstance {},
	goback: class extends self.ISpriteInstance {},
	waitforplayer: class extends self.ISpriteInstance {},
	dot: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	gameoverHome: class extends self.ISpriteInstance {},
	timerBallIcon: class extends self.ISpriteInstance {},
	timerCircle: class extends self.ISpriteInstance {},
	AutoBalltimetext: class extends self.ITextInstance {},
	yourteamName: class extends self.ITextInstance {},
	opponentTeamname: class extends self.ITextInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	cpl_totalOvers: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	tutorialMode: class extends self.ISpriteInstance {},
	missed: class extends self.ITextInstance {},
	tutPlayconsent: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	whatAShot_: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	timerCircle2: class extends self.ISpriteInstance {},
	timertxt: class extends self.ITextInstance {},
	PlayerOneIcon2: class extends self.ISpriteInstance {},
	TIMESUP: class extends self.ISpriteInstance {},
	camm: class extends self.ISpriteInstance {},
	Textlicense: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	cpl_TeamRankingText: class extends self.ITextInstance {},
	cpl_BSrankingText: class extends self.ITextInstance {},
	cpl_CSrankingText: class extends self.ITextInstance {},
	cpl_DDrankingText: class extends self.ITextInstance {},
	cpl_HSrankingText: class extends self.ITextInstance {},
	cpl_KRrankingText: class extends self.ITextInstance {},
	cpl_MWrankingText: class extends self.ITextInstance {},
	cpl_RCrankingText: class extends self.ITextInstance {},
	cpl_PLrankingText: class extends self.ITextInstance {},
	cpl_teamicons: class extends self.ISpriteInstance {},
	Splash: class extends self.ISpriteInstance {},
	cplobjects: class extends self.ISpriteInstance {},
	clojects: class extends self.ISpriteInstance {}
}